backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
media_folder_relative: true

collections:
  - name: "gemaelde" # Used in routes, e.g., /admin/collections/blog
    label: "Gem√§lde" # Used in the UI
    folder: "content/010-gemaelde/{{slug}}" # The path to the folder where the documents are stored
    path: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Demo", name: "demo", widget: "string", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
